# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bind-zone-parser}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Geoff Garside"]
  s.date = %q{2010-08-26}
  s.description = %q{Helps with parsing records and data from BIND Zone files}
  s.email = %q{geoff@geoffgarside.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bind-zone-parser.gemspec",
     "lib/bind-zone-parser.rb",
     "lib/bind/zone.rb",
     "lib/bind/zone_parser.rb",
     "lib/bind/zone_parser.rl",
     "test/examples/example.com.db",
     "test/helper.rb",
     "test/test_zone.rb",
     "test/test_zone_parser.rb"
  ]
  s.homepage = %q{http://github.com/geoffgarside/bind-zone-parser}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{BIND Zone file parser}
  s.test_files = [
    "test/helper.rb",
     "test/test_zone.rb",
     "test/test_zone_parser.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

